### ISSUE TITLE
Deploy bookdown via GitHub pages

### ISSUE THREAD

**Issue by lorenzwalthert** [EdwinTh/AMLwR#1]
E.g. with [tic](https://github.com/ropenscilabs/tic), like demonstrated here: https://github.com/ropenscilabs/tic.bookdown. Other approaches are using travis without tic, like https://github.com/tidyverse/style.

**Comment by EdwinTh** [comment]
Thanks! Will look into it soon

**Comment by EdwinTh** [comment]
Done, was some figuring out but it works now on https://edwinth.github.io/AMLwR/

**Comment by lorenzwalthert** [comment]
Nice
